import Navbar from '@/Components/Navbar/Navbar'
import './globals.css'
import Footer from '@/Components/Footer/Footer'

export const metadata = {
  title: 'Asana',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
